export const READ_SENSOR = "READ_SENSOR";
export const SET_SENSOR_DATA ="SET_SENSOR_DATA";
export const LOGIN="LOGIN";
export const LOGOUT ="LOGOUT";
export const SET_SENSOR_CONFIGURATION = "SET_SENSOR_CONFIGURATION";
export const SET_ACTUAL_SENSOR_STATUS = "SET_ACTUAL_SENSOR_STATUS"